### ISSUE TITLE
Wrong dimension of array in invert.jl

### ISSUE THREAD

**Issue by staffantackstrom** [JuliaData/SplitApplyCombine.jl#14]
Hello and thanks for a great package!

When calling invert with inner and outer arrays of different number of dimensions an exception is thrown.
I think it is line 40 in invert.jl
out = Array{Array{eltype(T),length(outersize)}}(undef, outersize)
that should be changed to
out = Array{Array{eltype(T),length(innersize)}}(undef, outersize)

(the first outersize is changed to innersize)

I don't mind changing it myself, but since I am pretty new with Julia, never used GitHub or written a test case and only do programming a few hours per year It might be better that someone who knows the code have a look at it?

**Comment by andyferris** [comment]
> Hello and thanks for a great package!

Thanks! :heart: 

> When calling invert with inner and outer arrays of different number of dimensions an exception is thrown.

Thanks for the bug report. I made a fix and test case in PR #15.

**Comment by andyferris** [comment]
I'm tagging v0.4.1 with this fix: https://github.com/JuliaLang/METADATA.jl/pull/19972
