### ISSUE TITLE
Rename SAC.jl to something else

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaData/SplitApplyCombine.jl#2]
What about SpApCo so _Spapco.jl_?

Reasons for renaming (in case we forget later)
- there is already as SAC.jl for seisimic data analysis
- SAC is too brief and may not satisfy package submission criteria

**Comment by andyferris** [comment]
Oh gosh, I was thinking something in *english* :laughing: 

+1 for renaming for given reasons.

I don't think *SplitApplyCombine* is too bad. (It's only used in `using SplitApplyCombine` and `Pkg.add("SplitApplyCombine")` so I don't think it's too long). But also generic stuff like *DataOps* or *Pliers* (from data pliers, `dplyr`, etc) or whatever are possible.

**Comment by andyferris** [comment]
The other thing is maybe moving this to the JuliaData organisation.

**Comment by xiaodaigh** [comment]
i vote for *SplitApplyCombine then homage to Hadley's paper*

**Comment by xiaodaigh** [comment]
yeah. if they let us move it there. also just realised u r in Australia as well. i am in Sydney. anyway happy to keep it in this repo until we find a more apt home

**Comment by andyferris** [comment]
Done. Also moved to JuliaData.
