### ISSUE TITLE
groupby taking a vector

### ISSUE THREAD

**Issue by mkborregaard** [JuliaData/SplitApplyCombine.jl#20]
`group` only takes a function, like `iseven`. But in many cases (like DataFrames.groupby) you want to split on a vector of groups.

**Comment by andyferris** [comment]
Could you please post a fuller example of the kind of behaviour you would like to see, for me?

**Comment by andyferris** [comment]
So on master, you can now do this:

```julia
julia> group([true,true,true,false,false], [1,2,3,4,5])
2-element Dictionaries.HashDictionary{Bool,Array{Int64,1}}
 false │ [4, 5]
  true │ [1, 2, 3]
```

Is this what you expected? It's also super useful in the context of a dataframe, like `group(df.col1, df.col2)`. 

That returns a vector, not a dataframe, though I imagine we could make `group(df.col1, df)` split up the table nicely (it already works for TypedTables). Furthermore, as sneak preview, I'm thinking of a `partition` function as a flattened version of `group` that works well with tables/dataframes, getting closer to a SQL and DataFrames.jl "group by"). (I need to do slightly more work on DIctionaries.jl before circling around to tables again though...)

**Comment by mkborregaard** [comment]
Oh, sorry I didn't see the comment above! Yes, that is exactly what I expected 💖  especially if it also would work for vectors of Ints, or Strings or any CategoricalArray, in addition to Bools? 
Your example on DataFrames sounds exactly like DataFrames.groupby, right?

**Comment by andyferris** [comment]
Cool. Yes it works for all types. 

`group` always returns a nested dictionary, whereas I thought `groupby` flattened out everything into a single table? Or am I mistaken?

**Comment by mkborregaard** [comment]
Ah, yes you are right.

**Comment by andyferris** [comment]
OK this seems resolved.

@JuliaRegistrator register

**Comment by andyferris** [comment]
Done :)
